// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	company "company-service/internal/application/company"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FetchPending provides a mock function with given fields: ctx, limit
func (_m *Repository) FetchPending(ctx context.Context, limit uint64) ([]company.OutboxEvent, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchPending")
	}

	var r0 []company.OutboxEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]company.OutboxEvent, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []company.OutboxEvent); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]company.OutboxEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkFailed provides a mock function with given fields: ctx, id, err
func (_m *Repository) MarkFailed(ctx context.Context, id uuid.UUID, err error) error {
	ret := _m.Called(ctx, id, err)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, error) error); ok {
		r0 = rf(ctx, id, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkPublished provides a mock function with given fields: ctx, id
func (_m *Repository) MarkPublished(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublished")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
