// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	company "company-service/internal/application/company"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OutboxStore is an autogenerated mock type for the OutboxStore type
type OutboxStore struct {
	mock.Mock
}

// Store provides a mock function with given fields: ctx, event
func (_m *OutboxStore) Store(ctx context.Context, event company.Event) error {
	ret := _m.Called(ctx, event)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, company.Event) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOutboxStore creates a new instance of OutboxStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboxStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboxStore {
	mock := &OutboxStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
